# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
xcode_workspace: Example/DOSChineseStringCompare.xcworkspace
xcode_scheme: Tests
xcode_sdk: iphonesimulator
#podfile: Example/Podfile

cache: cocoapods
before_install:
- export LANG=en_US.UTF-8
- env
- locale
- gem install cocoapods --quiet
- pod --version
- pod setup --silent
- pod repo update --silent
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet
- cd Example
- pod install
- cd ..
